### Welcome to Jekyll Webpack Boilerplate
#
# This config file contains the config of your webpages
# You may also want to update /config/webpack.pwa.js in case you want to generate a Progressive Web App

title: সংসদ নির্বাচন - এন্ড্রয়েড এপ
email: nurul@ferdo.us
description: বাংলাদেশের সকল সংসদ নির্বাচন
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
theme_color: '#c0ffee'
twitter_username: ferdous
github_username:  dynamicguy
author: Nurul Ferdous
logo: assets/images/large-logo.png
twitter:
  username: ferdous
social:
  name: Nurul Ferdous
  links:
    - https://twitter.com/ferdous
    - https://www.facebook.com/nurul.ferdous
    - https://www.linkedin.com/in/dynamicguy
    - https://plus.google.com/+dynamicguy
    - https://github.com/dynamicguy

languages: ["bn"]
ampdir: amp

### Google webmaster tools, Google Analytics, Doorbell and Cookie consent uncomment and put the API key
#webmaster_verifications:
#  google: verification_code
#google_analytics: id
#doorbell:
#  id: doorbell_id
#  appKey: doorbell_appKey

cookie_consent: true

### Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - octopress-minify-html
  - jekyll-multiple-languages-plugin
  - amp-jekyll

### Exclude from processing.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - _src
  - _images
  - LICENSE
  - package.json
  - README.md
  - webpack.config.js
  - yarn-error.log
  - yarn.lock
  - config
  - optimization-fix
  - optimization-fix-this-file-is-ignored.js
  - icon.png
